--- !map:HashWithIndifferentAccess 
detailed_info: |-
  <table>
  <tbody>
  <tr>
  <td  align="left" width="370">
  Contact us. Yes, don't hesitate. Our consultants would love<br/>to hear from you.<br/>Call us or fill the form and we will call you back asap.<br/><br/>
  Boulevard Saint Michel, 47<br/>B-1040 Brussels<br/>Belgium<br/>Tel. Belgium : +32 2 400 00 10<br/>Fax : +32 2 791 57 00<br/><br/>
  Email inquiries : info@istorm.be<br/>
  Send us your CV (or use the form) : cv@istorm.be<br/>
  <div><img src="http://188.165.47.165/temp/espresso.png" alt="want a coffee?" witdh="50" height="50" class="graphic-img" /><i>Want a cup of coffee ? Stop by our office.<br/>Check our location.</i></div>
  </td>
  <td><br/>
  <iframe width="370" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://www.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=istorm+agency,+boulevard+saint+michel,+1040+brussels&amp;sll=37.0625,-95.677068&amp;sspn=37.871902,78.662109&amp;ie=UTF8&amp;hq=istorm+agency,&amp;hnear=Boulevard+Saint-Michel,+1040,+Bruxelles,+Belgium&amp;ll=50.834777,4.405646&amp;spn=0.006295,0.006295&amp;output=embed"></iframe><small><a href="http://www.google.com/maps/place?cid=3384367642188563386&q=istorm+agency,+boulevard+saint+michel,+1040+brussels&hl=en&cd=1&cad=src:ppiwlink&ei=8VFETOKWBdT5OcediPUP&sig2=HD1EhIbZC9VGO7OX4zDQrQ" target="_blank">Click here to see our location on google maps</a></small>
  </td>
  </tr>
  </tbody>
  </table>
basic_info: "<img src=\"http://188.165.47.165/fellownation/istormapp/homepage.png\" alt=\"homepage\" witdh=\"740\"/>\r\n\
  <br/>\r\n\
  [ENGLISH] iStorm is a specialized recruitment & selection agency located in the Montgomery area in Brussels. We select highly specialized candidates for Belgium\xE2\x80\x99s top companies. We are a young and dynamic company with strong growth figures and we are looking to hire new enthusiastic colleagues.\r\n\
  <br/><br/>\r\n\
  Working at iStorm means joining a passionate team and a company culture that offers a good mix of hard work and fun.\r\n\
  Every consultant gets full ownership over a specific market and the responsibility to develop the customer portfolio. This means you will get challenged from day 1! iStorm also offers very diverse trainings: recruitment, sales, time management, negotiation techniques, etc.\r\n\
  <br/><br/>\r\n\
  Recognize yourself in the profile below? Then send us your CV now!\r\n\
  <br/><br/>\r\n\
  [DUTCH]\r\n\
  <br/>\r\n\
  iStorm is een gespecialiseerd selectiekantoor gelegen in Brussel in de Montgomery wijk en mag een aantal van de meest gerespecteerde bedrijven tot zijn cli\xC3\xABnten rekenen. Wij zijn een jong en dynamisch bedrijf, met sterke groeicijfers en zijn momenteel op zoek naar enthousiaste collegas!\r\n\
  <br/><br/>\r\n\
  Als medewerker bij iStorm kom je terecht in een hecht team en een bedrijfscultuur die een goede mix tussen fun en werk combineert. Elke Consultant krijgt vanaf dag \xC3\xA9\xC3\xA9n de verantwoordelijkheid om een specifieke markt en bijhorend klantenportfolio verder te ontwikkelen. Dit betekent een job met heel wat uitdaging en afwisseling. iStorm biedt dan ook heel uiteenlopende trainingen aan: recrutering, sales, marketing, time management, onderhandelingstechnieken, enz.\r\n\
  <br/><br/>\r\n\
  Herken je jezelf in het profiel en ben je op zoek naar een uitdaging? Stuur dan nu jouw CV door!\r\n\
  <br/><br/>\r\n\
  [FRENCH]\r\n\
  <br/>\r\n\
  iStorm est une agence sp\xC3\xA9cialis\xC3\xA9e en recrutement & s\xC3\xA9lection de personnel Informatique et Nouveau M\xC3\xA9dias. La soci\xC3\xA9t\xC3\xA9 est situ\xC3\xA9e juste \xC3\xA0 cote du rond point Montgomery \xC3\xA0 Bruxelles, facilement accessible en transport en commun. iStorm travaille avec le top 500 des soci\xC3\xA9t\xC3\xA9s belges et internationales. Nous sommes une soci\xC3\xA9t\xC3\xA9 jeune et dynamique avec une forte croissance et nous sommes \xC3\xA0 la recherche de nouveaux coll\xC3\xA8gues.\r\n\
  <br/><br/>\r\n\
  Travailler chez iStorm \xC3\xA9quivaut \xC3\xA0 rejoindre une culture d\xE2\x80\x99entreprise qui offre un bon m\xC3\xA9lange de fun et de responsabilit\xC3\xA9. Ici, pas besoin de beaucoup d\xE2\x80\x99exp\xC3\xA9rience pour recevoir de r\xC3\xA9elles responsabilit\xC3\xA9s. En effet, chaque consultant re\xC3\xA7oit une r\xC3\xA9gion et un portefeuille de clients a d\xC3\xA9velopper. Ceci constitue un v\xC3\xA9ritable challenge d\xC3\xA8s la premi\xC3\xA8re journ\xC3\xA9e! iStorm offre aussi des formations tr\xC3\xA8s vari\xC3\xA9es : recrutement, vente, gestion du temps, techniques de n\xC3\xA9gociations, etc.\r\n\
  <br/><br/>\r\n\
  Tu te reconnais dans le profil ci-dessous? Alors ne tarde pas \xC3\xA0 nous envoyer ton CV!\r\n\
  \r\n\
  \r\n\
  \r\n\
  \r\n"
